### ISSUE TITLE
Enh: SSL verification options

### ISSUE THREAD

**Issue by Vovan-VE** [centrifugal/phpcent#14]
Latest PHP has enables by default VERIFYPEER and VERIFYHOST.

1. Currently `Transport` in UNSAFE mode disables only VERIFYPEER keeping VERIFYHOST enabled.  <https://github.com/centrifugal/phpcent/blob/master/Transport.php#L33>
So, unable to use SSL in localhost with self-signed certificate.

2. It would be great to have ability to configure SSL specific options like CA file ~and private key file~.

**Comment by FZambia** [comment]
@Vovan-VE hello! This looks like a useful feature - could you send pull request?

**Comment by Vovan-VE** [comment]
To pass SSL host verification host name in URL must match with name in the certificate. So currently it is not possible to connect directly to IP like `https://127.0.0.1:8000` in SAFE manner.

As of PHP >= 7.0.7 and cURL >= 7.49 there is `CURLOPT_CONNECT_TO` option which should solve the problem. But I currently cannot use it to check this. Ubuntu 16.04 LTS currently has libcurl3 version 7.47.

**Comment by FZambia** [comment]
@Vovan-VE thanks for you contribution!
