### ISSUE TITLE
Cannot send / receive data to /api if Centrifugo use ssl

### ISSUE THREAD

**Issue by earx** [centrifugal/phpcent#18]
transport using solution cannot receive data from TLS, which is used by Centrifugo.
There is a possible solution

[CentrifugoTransport.php.zip](https://github.com/centrifugal/phpcent/files/1991528/CentrifugoTransport.php.zip)

**Comment by FZambia** [comment]
Hello! What's the error you get? Are you using self-signed certificates?

**Comment by earx** [comment]
Hi!
I use letsencrypt certificates.
There was no any error reported.
The transport just returned empty data.

**Comment by FZambia** [comment]
Could you show the diff of your suggested fix instead of zip file?

**Comment by FZambia** [comment]
Closing as no answer from op for a long time
