### ISSUE TITLE
Migrate library for Centrifugo v2

### ISSUE THREAD

**Issue by FZambia** [centrifugal/phpcent#21]
Does someone interested in migrating this library to support Centrifugo v2? We need 2 things:

* migrate code to work with v2 (I can help explaining differences between v1 and v2 API)
* make automatic releases over travis CI – so creating tag in this lib resulted in automatic uploading of new release to convenient PHP registry

**Comment by hetao29** [comment]
try to use https://github.com/hetao29/phpcent2

**Comment by FZambia** [comment]
phpcent v2 released
