### ISSUE TITLE
Got error: Notice: Undefined variable: response

### ISSUE THREAD

**Issue by Arkemlar** [centrifugal/phpcent#30]
PHP writes:
`Notice: Undefined variable: response`
![image](https://user-images.githubusercontent.com/19671202/52750727-1d393d80-2ffe-11e9-8c67-af6aa009ab11.png)
Checked code, thats really missing $response variable.

**Comment by FZambia** [comment]
Hi, this is fixed in latest version, looks like you are using v2.0.0
