### ISSUE TITLE
Query result parsed without ASSOC option of json_decode?!

### ISSUE THREAD

**Issue by Arkemlar** [centrifugal/phpcent#31]
I was quite surprised when `presence_stats` returned me object instead of array, I looked into sources and found: 
```
    private function send($method, $params = [])
    {
	    $response = \json_decode($this->request($method, $params));
	    if (JSON_ERROR_NONE !== json_last_error()) {
          throw new \Exception(
            'json_decode error: ' . json_last_error_msg()
          );
        }
        return $response;
    }
```
Im wondering who ever uses `json_decode` without `assoc` option, at least there must be an option for it, but not hardcoded implicit `false`.

**Comment by FZambia** [comment]
Hello, please send pull request with a client option to use `assoc` while decoding if you prefer to use it.
