### ISSUE TITLE
PHP 7.2 Compile Error

### ISSUE THREAD

**Issue by tQuant** [centrifugal/phpcent#33]
Hi, I got PHP Compile Error on PHP 7.2

'Default value for parameters with a class type hint can only be NULL' in /usr/local/www/h/vendor/sl4mmer/phpcent/Client.php:18

public function __construct(string $url, string $apikey = '', string $secret = '')

**Comment by FZambia** [comment]
Hello, are you sure you run it with PHP 7.2? I can't reproduce it with this version. And I suppose this type of error should happen in PHP < 7.0.0 (https://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration).

**Comment by tQuant** [comment]
Apparently I confused the server and this error was on php 5.6

**Comment by FZambia** [comment]
I suppose related pr should fix all problems - could you look at it?  As I am not a PHP developer all these things are pretty new to me.

**Comment by tQuant** [comment]
Checked, works fine

**Comment by FZambia** [comment]
Thanks! Will release new version later today as soon as I come home from work.

**Comment by FZambia** [comment]
@tQuant just created new tag: v2.1.0 - I am not sure that integration with composer currently works as package maintained by @sl4mmer. If there are any problems please report and I will try to transfer repo somehow, maybe create new package name if needed.
