### ISSUE TITLE
Sync package releases with packagist

### ISSUE THREAD

**Issue by vitalybaev** [centrifugal/phpcent#35]
The latest version on packagist is `2.0.0` since actual version is `2.1.0`.
Update, please

**Comment by FZambia** [comment]
Unfortunately my attempts to sync new version to Packagist by simply creating new tag and updating version in composer.json failed - can't understand why without @sl4mmer , looks like I need to change package name and create it under my personal account

**Comment by FZambia** [comment]
@vitalybaev do you know a better way maybe? I am not familiar with PHP ecosystem so can miss sth.

**Comment by vitalybaev** [comment]
@FZambia usually I set up automatic sync at packagist.org. Once it's enabled, creating a release on GitHub automatically publishes it on packagist.org
So, if the packagist account isn't yours then you have two ways:
1. Tell account owner to enable automatic sync
2. Publish package from your packagist account

I can't tell you which way is the most appropriate for this case.

**Comment by FZambia** [comment]
It worked automatically before (ex. v2.0.0). But at moment sth went wrong and looks like @sl4mmer can't maintain this repo anymore.

**Comment by FZambia** [comment]
Released new major version 3.0.0 under new name `centrifugal/phpcent`. Interesting but the old package somehow synchronized too after this... I suppose the `sl4mmer/phpcent` package will be synchronized until @sl4mmer will mark project as abandoned. @vitalybaev could you check that 3.0.0 works for you?

**Comment by vitalybaev** [comment]
@FZambia Sorry for the late answer. Now both packages are working good! Maybe there was a temporary sync error, I don't know
