### ISSUE TITLE
Disable curl's IPv6 host name resolution

### ISSUE THREAD

**Issue by SteveTherrien** [centrifugal/phpcent#44]
I'm running into a problem where my application logs this error with phpcent several times each day:
```
cURL error: Resolving timed out after 2512 milliseconds
```

I'm using an internal DNS server and the timeout is 2s. We're IPv4 internally and don't use/publish IPv6 records.

Forcing IPv4 resolution with `curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);` solves the problem, and haven't had a single error in over 20 days, but that capability isn't exposed. 

Would it be possible to let this option be set?

**Comment by FZambia** [comment]
@SteveTherrien hello, could you send pr? I suppose sth like `forceIpResolveV4` method makes sense.
