### ISSUE TITLE
DEPRECATED  hash_hmac() passing null to parameter

### ISSUE THREAD

**Issue by Brainiac24** [centrifugal/phpcent#57]
There is a deprecation warning for php 8.1 in `vendor/centrifugal/phpcent/src/Client.php` on line 403 in `"centrifugal/phpcent": "^5.1" version` when calling `$client->generateConnectionToken($userId)` function.

Raw php warning message:
`DEPRECATED  hash_hmac(): Passing null to parameter #3 ($key) of type string is deprecated in vendor/centrifugal/phpcent/src/Client.php on line 403.`

**Comment by FZambia** [comment]
Hello, have you set secret before calling sign? Do not understand how $key may be null otherwise.

**Comment by FZambia** [comment]
Closing since no response from op.
