### ISSUE TITLE
Doesn't work when many requests need to be made

### ISSUE THREAD

**Issue by hrustbb2** [centrifugal/phpcent#58]
Doesn't work when many requests need to be made

**Comment by hrustbb2** [comment]
ну чё там?

**Comment by FZambia** [comment]
I am not able to reproduce the issue, added this test:

```php
    public function testPublishMultipleTimes()
    {
        for ($i = 0; $i < 5000; $i++) {
            $this->testPublish();
        }
    }
```

To [our test suite](https://github.com/centrifugal/phpcent/blob/master/tests/ClientTest.php) - and it works fine.

**Comment by aryzhkovg8** [comment]
@hrustbb2 Can you provide больше деталей для reproduce этого бага?

**Comment by FZambia** [comment]
Closing as can't reproduce.
