### ISSUE TITLE
Subject: Inquiry Regarding token_hmac_secret_key Usage for Subscription Token Generation

### ISSUE THREAD

**Issue by EVOSandru6** [centrifugal/phpcent#61]
Hello,

I hope this message finds you well. I've been exploring your repository with great interest, particularly regarding its capabilities around message publishing and subscription token generation. While reviewing the code, I noticed that there seems to be no mention of token_hmac_secret_key, which, as I understand, is essential for generating JWT tokens for subscription purposes in certain contexts.

Could you kindly clarify whether the tool is designed solely for publishing messages, without the capacity to generate tokens for subscribing? If it indeed lacks this functionality, could you please advise on the recommended approach to implement token generation for subscriptions? Any guidance or suggestions you could provide would be immensely appreciated.

Thank you for your time and for the efforts you've put into developing this tool. I look forward to your response.

Best regards!

**Comment by FZambia** [comment]
Hello, missed this issue. There is a function to generate subscription JWT:

https://github.com/centrifugal/phpcent/blob/59717fac8659b7144993e419d5929f2109a26052/src/Client.php#L345

But any other JWT library may be used to generate Centrifugo connection and subscription tokens.
