### ISSUE TITLE
info() fails with the new HTTP API format

### ISSUE THREAD

**Issue by SteveTherrien** [centrifugal/phpcent#64]
I'm using phpcent 6.0.0 with Centrifugo 5.4.1.

Requesting the server info using `info()` fails with a 400 Bad Request. The server logs this:
```
error decoding API request body error="json: cannot unmarshal array into Go value of type apiproto.InfoRequest" path=/api/info
```

This is because `info()` doesn't have parameters to send:
https://github.com/centrifugal/phpcent/blob/463e991ed7673fd8d1f07be98d806a10bab838da/src/Client.php#L294

causing `send($method, $params = array())` to pass an empty array in `request($method, $params)` when making the request and encoding to JSON:

https://github.com/centrifugal/phpcent/blob/463e991ed7673fd8d1f07be98d806a10bab838da/src/Client.php#L435

The problem is that `\json_encode($params)` encodes empty arrays as `[]` instead of `{}`, which the server doesn't expect:

**Error**
```bash
curl -i --header "Content-Type: application/json" \
  --header "X-API-Key: API_KEY" \
  --request POST \
  --data '[]' \
  http://localhost:8000/api/info


HTTP/2 400
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
date: Wed, 26 Jun 2024 20:02:22 GMT
content-length: 12

Bad Request
```

**Success**
```bash
curl -i --header "Content-Type: application/json" \
  --header "X-API-Key: API_KEY" \
  --request POST \
  --data '{}' \
  http://localhost:8000/api/info

HTTP/2 200
content-type: application/json
date: Wed, 26 Jun 2024 20:02:43 GMT

{"result":{"nodes":[{"uid":"9fdcca17-ece7-...
```

`json_encode` supports a [JSON_FORCE_OBJECT](https://www.php.net/manual/en/json.constants.php#constant.json-force-object) flag, but that causes problems when encoding index-based arrays.

[This comment](https://www.php.net/manual/en/function.json-encode.php#127741) instead suggests casting with `(object)` to cause empty arrays to encode as `{}` while preserving index-based arrays:
```php
curl_setopt($ch, CURLOPT_POSTFIELDS, \json_encode((object)$params));
```

An example comparing the different methods is at https://3v4l.org/H0BL5#v7.0.0

**Comment by FZambia** [comment]
Hello @SteveTherrien 

Many thanks for detailed report! Maybe you want to sent pull request for this? Otherwise, I will try to fix soon.

**Comment by ingfdoaguirre** [comment]
Hi, I'm getting the same error with the new 6.0.1 version 

`{"level":"error","error":"json: cannot unmarshal number into Go struct field PublishRequest.channel of type string","path":"/api/publish","time":"2024-08-24T19:14:58Z","message":"error decoding API request body"}`
